# Go 1.21 Dockerfile
FROM golang:1.21 AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy the Go demo code into the container
COPY . .

# Build the Go application
RUN go mod init golang_demo && \
    go mod tidy && \
    go build -o main .

# Use a lightweight image to run the Go binary
FROM gcr.io/distroless/base-debian12

# Copy the compiled binary from the builder
COPY --from=builder /app/main /main

EXPOSE 6060

# Run the binary
ENTRYPOINT ["/main"]
